apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-ant
  labels:
    app: nginx-ant

spec:
  replicas: 2
  strategy:
    rollingUpdate:  # no downtime on replica update can be configured through this conf
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: nginx-ant
  template:
    metadata:
      labels:
        app: nginx-ant
    spec:
      containers:
        - image: nginx:1.22.0
          name: nginx-ant
          env:
            - name: SOME_ENV
              value: $SOME_ENV
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8080

# http://localhost:81/